version: '2'
services:
  mysql_master:
    image: mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=PpA4q38F"
    volumes:
      - ./config/mysql-master:/etc/mysql/conf.d/
      - ./data/mysql-master:/var/lib/mysql/
  mysql_slave:
    image: mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=uSA8dppL"
    volumes:
      - ./config/mysql-slave:/etc/mysql/conf.d/
      - ./data/mysql-slave:/var/lib/mysql/
  mysql_connect:
    image: mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=n7rgx3yw"
      - "MYSQL_SLAVE_PASSWORD=uSA8dppL"
      - "MYSQL_MASTER_PASSWORD=PpA4q38F"
      - "MYSQL_REPLICATION_USER=repl_usr"
      - "MYSQL_REPLICATION_PASSWORD=Rtmghtzv"
    volumes:
      - ./script-replication-connector.sh:/tmp/script-replication-connector.sh
    command: /bin/bash -x /tmp/script-replication-connector.sh